language: python

notifications:
  email: false
  
matrix:
  include:
  
    - os: linux
      sudo: required
      services: docker
      python: '3.5'

    - os: linux
      sudo: required
      services: docker
      python: '3.6'

    - os: linux
      dist: xenial    # required for Python 3.7 (travis-ci/travis-ci#9069)
      sudo: required
      services: docker
      python: '3.7'
  
before_install:
- pip install pep8
- pip install flake8
before_script:
- flake8 --show-source --ignore=F811,W293,W391,W292,W291,E252,W504 --max-line-length=79 --exclude='__init__.py, conf.py'
script:
- pytest --doctest-modules -v efficient_apriori
