language: python
notifications:
  email: false
python:
- '3.6'
before_install:
- pip install pep8
- pip install flake8
before_script:
- flake8 --show-source --ignore=F811,W293,W391,W292,W291 --max-line-length=79 --exclude='__init__.py'
script:
- pytest --doctest-modules -v
deploy:
  provider: pypi
  user: tommyod
  password:
    secure: en3EqG/43J/1q82pV7aTZCsPo9TYn79VqRH/HuZnMrnKO+8io9CMJwrsSFeXG788em+I+ZGn3ciEicJnsL80NQZz3J21/Hia418YqP+/iw9Sfyzi+T4mfs7xsA5i4fI56P4DEyflhSCL9u2EiB8ZE/CNGgzEbsXld+W/xBtaG/DYLln7KvL4qrNh0nfh+YCMsishWvW6upjOakRigoI0NZ88miIPvomZzmTLx2ZkpsqBRJojb0zm3O7Zs2M7KAAf9tSaEIRUN64CQvGotUSbMoL8nDAhwj33DSYp+xlVUJdCcE5t91DvFsF0Osjqxt4E5A3jst/3EsjxF5zshRQxAN1fqLr2xxidTN1+Uln9TvqNjkvV13j5Mi0nE6Xm5boo/8AVFQYU/IoNdcK5bfhCiZp4bIT1XipteVmgffI2Z16S2PoO74CpPeRwdz0tK4M9CzZpJvz2KOQqWiBSLnfJVOc2TAjQ9OhX6ZxXBaCHW7qgtXD/THlmemS5WYJiLHBh5IaynbNL36mbwEOkMG0Kd3Xg4ZaWJR47R+8xJT5GSUA+PB9O21JqbI4076om+M4u+is6wWuDpLCY/8j3nc8BTzTxqsEOoZIK5sQIJOEgk8pgUXGon5ukWPsvaH8kTN3bEzy2eYMNbSVRgM2/l9YoJ/O9zSxc/nUm4DHGhBm1JWw=
  on:
    tags: true
  distributions: sdist
